/* eslint-disable @next/next/inline-script-id */
/* eslint-disable @next/next/no-sync-scripts */
/* eslint-disable react/no-unescaped-entities */
/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>SKY BOOK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        />
        <body>
          <script type="text/javascript" src="/slieshow.js"></script>
        </body>
      </Head>

      <main className={styles.main}>
        <div>
          <div className={styles["slideshow-container"]}>
            <div className={styles["mySlides fade"]}>
              <div className={styles["numbertext"]}>1 / 3</div>
              <img
                src="https://res.cloudinary.com/assjavascript/image/upload/v1658484278/assignment-nextjs/slide_1_img_pavlsg.webp"
                style={{ width: "100%" }}
              />
              <div className={styles["text"]}>SKYBOOK</div>
            </div>
            <div className={styles["mySlides fade"]}>
              <div className={styles["numbertext"]}>2 / 3</div>
              <img
                src="https://res.cloudinary.com/assjavascript/image/upload/v1658484279/assignment-nextjs/slide_3_img_s0pfxv.webp"
                style={{ width: "100%" }}
              />
              <div className={styles["text"]}>SKYBOOK</div>
            </div>
            <div className={styles["mySlides fade"]}>
              <div className={styles["numbertext"]}>3 / 3</div>
              <img
                src="https://res.cloudinary.com/assjavascript/image/upload/v1658484278/assignment-nextjs/slide_2_img_oqy8ih.webp"
                style={{ width: "100%" }}
              />
              <div className={styles["text"]}>SKYBOOK</div>
            </div>
          </div>
          <br />
          <div style={{ textAlign: "center" }}>
            <span className={styles["dot"]} />
            <span className={styles["dot"]} />
            <span className={styles["dot"]} />
          </div>
          <div style={{ marginTop: 40 }}>
            <div className={styles["container"]}>
              <div className={styles["class-box"]}>
                <h2 className={styles["hTitle"]}>Danh Mục Nổi Bật</h2>
              </div>
              <div className={styles["content-category"]}>
                <div className={styles["category-detail"]}>
                  <div className={styles["img-category"]}>
                    <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484275/assignment-nextjs/categorybanner_1_img_rcbvbl.webp" />
                  </div>
                  <h3 className={styles["title-category"]}>Văn phòng phẩm</h3>
                  <div className={styles["categorylink-btn"]}>
                    <a href="/collections/all">Xem ngay</a>
                    <i className="fa fa-angle-right" aria-hidden="true" />
                  </div>
                </div>
                <div
                  style={{ background: "#faf4eb", marginLeft: 15 }}
                  className={styles["category-detail"]}
                >
                  <div className={styles["img-category"]}>
                    <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484275/assignment-nextjs/categorybanner_2_img.webp_g6kvg3.webp" />
                  </div>
                  <h3 className={styles["title-category"]}>Sách giáo khoa</h3>
                  <div className={styles["categorylink-btn"]}>
                    <a href="/collections/all">Xem ngay</a>
                    <i className="fa fa-angle-right" aria-hidden="true" />
                  </div>
                </div>
                <div
                  style={{ background: "#f4e6e5", marginLeft: 15 }}
                  className={styles["category-detail"]}
                >
                  <div className={styles["img-category"]}>
                    <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484275/assignment-nextjs/categorybanner_3_img_n9310o.webp" />
                  </div>
                  <h3 className={styles["title-category"]}>Sức khỏe</h3>
                  <div className={styles["categorylink-btn"]}>
                    <a href="/collections/all">Xem ngay</a>
                    <i className="fa fa-angle-right" aria-hidden="true" />
                  </div>
                </div>
                <div
                  style={{ background: "#e6f2f4", marginLeft: 15 }}
                  className={styles["category-detail"]}
                >
                  <div className={styles["img-category"]}>
                    <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484275/assignment-nextjs/categorybanner_4_img_tvphhi.webp" />
                  </div>
                  <h3 className={styles["title-category"]}>Dụng cụ học tập</h3>
                  <div className={styles["categorylink-btn"]}>
                    <a href="/collections/all">Xem ngay</a>
                    <i className="fa fa-angle-right" aria-hidden="true" />
                  </div>
                </div>
                <div
                  style={{ background: "#fff6f6", marginLeft: 15 }}
                  className={styles["category-detail"]}
                >
                  <div className={styles["img-category"]}>
                    <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/categorybanner_5_img_drawpm.webp" />
                  </div>
                  <h3 className={styles["title-category"]}>Sách tiếng Anh</h3>
                  <div className={styles["categorylink-btn"]}>
                    <a href="/collections/all">Xem ngay</a>
                    <i className="fa fa-angle-right" aria-hidden="true" />
                  </div>
                </div>
              </div>
            </div>
            <>
              <section className={styles["home-collection-1"]}>
                <div className={styles["container"]}>
                  <div className={styles["wrapper-content"]}>
                    <div className={styles["section-heading"]}>
                      <div className={styles["box-heading"]}>
                        <h2 className={styles["hTitle"]}>
                          Sản Phẩm Khuyến Mại
                        </h2>
                      </div>
                      <div id={styles["countdown"]}>
                        <h3 style={{ color: "white", marginRight: 20 }}>
                          Kết thúc sau :
                        </h3>
                        <ul>
                          <li>
                            <span id="days" />
                            Ngày
                          </li>
                          <li>
                            <span id="hours" />
                            Giờ
                          </li>
                          <li>
                            <span id="minutes" />
                            Phút
                          </li>
                          <li>
                            <span id="seconds" />
                            Giây
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div className={styles["listProduct"]}>
                      <div
                        className={styles["owl-item"]}
                        style={{ width: 236, marginRight: 15 }}
                      >
                        <div className={styles["product-inner"]}>
                          <div className={styles["product-books-1"]}>
                            <div className={styles["proloop-img"]}>
                              <div className={styles["pro-sale"]}>
                                <span>-24%</span>
                              </div>
                              <div
                                className={styles["img-product"]}
                                style={{ height: 215 }}
                              >
                                <Link href="/product-detail/{{productList._id}}">
                                  <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg"></img>
                                </Link>
                              </div>
                              <div className={styles["img-sale"]}>
                                <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                              </div>
                              .
                            </div>
                            <div className={styles["proloop-detail"]}>
                              <p className={styles["pro-vendor"]}>
                                First News - Trí Việt
                              </p>
                              <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                              <p className={styles["pro-price"]}>
                                <span className={styles["price"]}>
                                  150,000đ
                                </span>
                                <span className={styles["price-del"]}>
                                  200,000đ
                                </span>
                              </p>
                            </div>
                            <div
                              className={styles["proloop-actions"]}
                              data-vrid={1079696682}
                            >
                              <div className={styles["proloop-actions__inner"]}>
                                <div className={styles["actions-primary"]}>
                                  <button
                                    type="submit"
                                    className={
                                      styles["btn-proloop-cart add-to-cart"]
                                    }
                                    style={{ display: "flex" }}
                                  >
                                    <span className={styles["btnadd"]}>
                                      Thêm vào giỏ
                                    </span>
                                    <span
                                      className={styles["btnico"]}
                                      style={{
                                        borderRadius: "50%",
                                        marginLeft: 65,
                                        border: "1px solid gray",
                                        background: "yellow",
                                        padding: 5,
                                      }}
                                    >
                                      <svg
                                        id="svg"
                                        xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 -13 456.75885 456"
                                      >
                                        <path d="m150.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                        <path d="m446.855469 94.035156h-353.101563l-7.199218-40.300781c-4.4375-24.808594-23.882813-44.214844-48.699219-48.601563l-26.101563-4.597656c-5.441406-.96875-10.632812 2.660156-11.601562 8.097656-.964844 5.441407 2.660156 10.632813 8.101562 11.601563l26.199219 4.597656c16.53125 2.929688 29.472656 15.871094 32.402344 32.402344l35.398437 199.699219c4.179688 23.894531 24.941406 41.324218 49.199219 41.300781h210c22.0625.066406 41.546875-14.375 47.902344-35.5l47-155.800781c.871093-3.039063.320312-6.3125-1.5-8.898438-1.902344-2.503906-4.859375-3.980468-8-4zm-56.601563 162.796875c-3.773437 12.6875-15.464844 21.367188-28.699218 21.300781h-210c-14.566407.039063-27.035157-10.441406-29.5-24.800781l-24.699219-139.398437h336.097656zm0 0" />
                                        <path d="m360.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                      </svg>
                                    </span>
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={styles["box-link"]}>
                      <a
                        href="/collections/onsale"
                        className={styles["button"]}
                      >
                        Xem tất cả
                        <svg
                          style={{
                            overflow: "hidden",
                            verticalAlign: "middle",
                            display: "none",
                          }}
                          version="1.1"
                          xmlns="http://www.w3.org/2000/svg"
                          xmlnsXlink="http://www.w3.org/1999/xlink"
                          x="0px"
                          y="0px"
                          viewBox="0 0 32 32"
                          xmlSpace="preserve"
                        >
                          <circle
                            className={styles["st0"]}
                            cx={16}
                            cy={16}
                            r={13}
                          />
                          <polyline
                            className={styles["st0"]}
                            points="14,11.8 18.2,16 14,20.2 "
                          />
                        </svg>
                      </a>
                    </div>
                  </div>
                </div>
              </section>
            </>
            <>
              <section
                className={styles["home-collection-navtabs"]}
                style={{ paddingBottom: 70 }}
              >
                <div className={styles["container"]}>
                  <div className={styles["section-heading"]}>
                    <div className={styles["box-header"]}>
                      <h2 className={styles["hTitle"]}>Tác Phẩm Nổi Bật</h2>
                    </div>
                    <div className={styles["box-tablist"]}>
                      <ul
                        className={
                          styles["nav collection-navtabs-title pills-tab"]
                        }
                        style={{ display: "flex" }}
                      >
                        <li className={styles["nav-link"]}>
                          <a
                            className={styles["nav-link nav-main"]}
                            data-handle="/collections/moi-phat-hanh"
                            data-toggle="tab"
                          >
                            Sách văn học
                          </a>
                        </li>
                        <li className={styles["nav-link"]}>
                          <a
                            className={styles["nav-link "]}
                            data-handle="/collections/sach-ban-chay"
                            data-toggle="tab"
                            href="#collection-tabs-2"
                          >
                            Sách kinh tế
                          </a>
                        </li>
                        <li className={styles["nav-link"]}>
                          <a
                            data-handle
                            data-toggle="tab"
                            href="#collection-tabs-3"
                          >
                            Sách lịch sử
                          </a>
                        </li>
                        <li className={styles["nav-link"]}>
                          <a
                            className={styles["nav-link "]}
                            data-handle
                            data-toggle="tab"
                            href="#collection-tabs-4"
                          >
                            Sách kĩ năng
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div className={styles["tab-cotent"]}>
                    <div
                      className={styles["listProduct"]}
                      style={{
                        display: "grid",
                        gridTemplateColumns: "1fr 1fr 1fr 1fr 1fr 1fr",
                      }}
                    >
                      <div
                        className={styles["owl-item"]}
                        style={{
                          width: 220,
                          padding: 0,
                          border: "1px solid #eae4e8",
                        }}
                      >
                        <div className={styles["product-inner"]}>
                          <div
                            className={styles["product-books-1"]}
                            style={{ border: "none" }}
                          >
                            <div className={styles["proloop-img"]}>
                              <div className={styles["pro-sale"]}>
                                <span>-24%</span>
                              </div>
                              <div
                                className={styles["pro-sale"]}
                                style={{ background: "#eae4e8" }}
                              >
                                <span style={{ width: 180 }}>Hết Hàng</span>
                              </div>
                              <div
                                className={styles["img-product"]}
                                style={{ height: 215 }}
                              >
                                <Link href="/product-detail/{{product._id}}">
                                  <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484278/assignment-nextjs/sale-4_opuiac.webp" />
                                </Link>
                              </div>
                              <div className={styles["img-sale"]}>
                                <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                              </div>
                              .
                            </div>
                            <div className={styles["proloop-detail"]}>
                              <p className={styles["pro-vendor"]}>
                                First News - Trí Việt
                              </p>
                              <h3>
                                Nóng Giận Là Bản Năng , Tĩnh Lặng Là Bản Lĩnh
                              </h3>
                              <p className={styles["pro-price"]}>
                                <span className={styles["price"]}>62,000đ</span>
                                <span className={styles["price-del"]}>
                                  80,000đ
                                </span>
                              </p>
                            </div>
                            <div
                              className={styles["proloop-actions"]}
                              data-vrid={1079696682}
                            >
                              <div className={styles["proloop-actions__inner"]}>
                                <div className={styles["actions-primary"]}>
                                  <button
                                    type="submit"
                                    className={
                                      styles["btn-proloop-cart add-to-cart"]
                                    }
                                    style={{ width: 180 }}
                                    disabled
                                  >
                                    <span className={styles["btnsold"]}>
                                      Hết hàng
                                    </span>
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </>
            <section className={styles["home-collection-2"]}>
              <div className={styles["container"]}>
                <div className={styles["section-heading"]}>
                  <div className={styles["box-header"]}>
                    <h2 className={styles["hTitle"]}>Sách Kinh Doanh</h2>
                  </div>
                </div>
                <div
                  className={styles["listProduct"]}
                  style={{
                    display: "grid",
                    gridTemplateColumns: "1fr 1fr 1fr",
                  }}
                >
                  <div
                    className={styles["owl-item"]}
                    style={{ width: 220, padding: 0 }}
                  >
                    <div
                      className={styles["product-inner"]}
                      style={{ width: 435, border: "1px solid #eae4e8" }}
                    >
                      <div
                        className={styles["product-books-1"]}
                        style={{
                          height: 250,
                          display: "flex",
                          alignItems: "center",
                        }}
                      >
                        <div className={styles["proloop-img"]}>
                          <div
                            className={styles["pro-sale"]}
                            style={{ marginLeft: 30 }}
                          >
                            <span>-24%</span>
                          </div>
                          <div className={styles["img-product"]}>
                            <img
                              src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg"
                              style={{
                                width: 130,
                                objectFit: "contain",
                                marginLeft: 30,
                              }}
                            />
                          </div>
                          <div
                            className={styles["img-sale"]}
                            style={{ bottom: 20, marginLeft: 30 }}
                          >
                            <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                          </div>{" "}
                          .
                        </div>
                        <div className={styles["proloop-detail"]}>
                          <p className={styles["pro-vendor"]}>
                            First News - Trí Việt
                          </p>
                          <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                          <p className={styles["pro-price"]}>
                            <span className={styles["price"]}>58,000₫</span>
                            <span className={styles["price-del"]}>76,000₫</span>
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={styles["owl-item"]}
                    style={{ width: 220, padding: 0 }}
                  >
                    <div
                      className={styles["product-inner"]}
                      style={{ width: 435, border: "1px solid #eae4e8" }}
                    >
                      <div
                        className={styles["product-books-1"]}
                        style={{
                          height: 250,
                          display: "flex",
                          alignItems: "center",
                        }}
                      >
                        <div className={styles["proloop-img"]}>
                          <div
                            className={styles["pro-sale"]}
                            style={{ marginLeft: 30 }}
                          >
                            <span>-24%</span>
                          </div>
                          <div className={styles["img-product"]}>
                            <img
                              src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg"
                              style={{
                                width: 130,
                                objectFit: "contain",
                                marginLeft: 30,
                              }}
                            />
                          </div>
                          <div
                            className={styles["img-sale"]}
                            style={{ bottom: 20, marginLeft: 30 }}
                          >
                            <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                          </div>{" "}
                          .
                        </div>
                        <div className={styles["proloop-detail"]}>
                          <p className={styles["pro-vendor"]}>
                            First News - Trí Việt
                          </p>
                          <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                          <p className={styles["pro-price"]}>
                            <span className={styles["price"]}>58,000₫</span>
                            <span className={styles["price-del"]}>76,000₫</span>
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div
                    className={styles["owl-item"]}
                    style={{ width: 220, padding: 0 }}
                  >
                    <div
                      className={styles["product-inner"]}
                      style={{ width: 435, border: "1px solid #eae4e8" }}
                    >
                      <div
                        className={styles["product-books-1"]}
                        style={{
                          height: 250,
                          display: "flex",
                          alignItems: "center",
                        }}
                      >
                        <div className={styles["proloop-img"]}>
                          <div
                            className={styles["pro-sale"]}
                            style={{ marginLeft: 30 }}
                          >
                            <span>-24%</span>
                          </div>
                          <div className={styles["img-product"]}>
                            <img
                              src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg"
                              style={{
                                width: 130,
                                objectFit: "contain",
                                marginLeft: 30,
                              }}
                            />
                          </div>
                          <div
                            className={styles["img-sale"]}
                            style={{ bottom: 20, marginLeft: 30 }}
                          >
                            <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                          </div>{" "}
                          .
                        </div>
                        <div className={styles["proloop-detail"]}>
                          <p className={styles["pro-vendor"]}>
                            First News - Trí Việt
                          </p>
                          <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                          <p className="pro-price">
                            <span className="price">58,000₫</span>
                            <span className="price-del">76,000₫</span>
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div style={{ textAlign: "center", marginTop: 40 }}>
                  <span className={styles["dot"]} />
                  <span className={styles["dot"]} />
                  <span className={styles["dot"]} />
                </div>
              </div>
            </section>
            <section className={styles["home-collection-3"]}>
              <div className={styles["container"]}>
                <div className={styles["section-heading"]}>
                  <div className={styles["box-header"]}>
                    <h2 className={styles["hTitle"]}>Khuyến Mãi Hôm Nay</h2>
                  </div>
                </div>
                <div className={styles["home-collection-sale"]}>
                  <div className={styles["content-product-sale"]}>
                    <div className={styles["img-collection-sale"]}>
                      <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/home_collection_banner_afsaxh.png" />
                    </div>
                    <div className={styles["text-sale"]}>
                      <h2>Thông Điệp Sách</h2>
                      <p>
                        Sách có lẽ rằng là một trong những ý tưởng quan trọng và
                        vĩ đại nhất của con người. Mỗi cuốn sách là kết tinh từ
                        tri thức và đời sống, đọc sách không chỉ là một sở
                        trường thích nghi mà còn là con đường ngắn nhất để tiếp
                        cận với nền văn minh của quả đât. Ngày nay, với sự tăng
                        trưởng của những phương tiện đi lại điện tử, sách trở
                        nên mờ nhạt trong đời sống của mọi người, không còn
                        nhiều người hiểu được giá trị to lớn mà mộ quyển sách
                        hoàn toàn có thể mang lại, đó thực sự là một điều đáng
                        buồn. Sau đây là những câu nói nói về giá trị của sách
                        để ta khẳng định chắc chắn sách cần được trở lại với
                        đúng vai trò của nó, chứ không đơn thuần chỉ để vui chơi
                      </p>
                      <span
                        style={{
                          float: "right",
                          fontWeight: 600,
                        }}
                      >
                        "Đọc sách cho ta thêm kiến thức và sự hiểu biết"
                      </span>
                    </div>
                  </div>
                  <div className={styles["listProduct-sale"]}>
                    <div
                      className={styles["listProduct"]}
                      style={{
                        display: "grid",
                        gridTemplateColumns: "1fr 1fr 1fr 1fr",
                      }}
                    >
                      <div
                        className={styles["owl-item"]}
                        style={{
                          width: 220,
                          padding: 0,
                          border: "1px solid #eae4e8",
                        }}
                      >
                        <div className={styles["product-inner"]}>
                          <div
                            className={styles["product-books-1"]}
                            style={{ border: "none" }}
                          >
                            <div className={styles["proloop-img"]}>
                              <div className={styles["pro-sale"]}>
                                <span>-24%</span>
                              </div>
                              <div
                                className={styles["img-product"]}
                                style={{ height: 215 }}
                              >
                                <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg" />
                              </div>
                              <div className={styles["img-sale"]}>
                                <img src=" https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                              </div>
                              .
                            </div>
                            <div className={styles["proloop-detail"]}>
                              <p className={styles["pro-vendor"]}>
                                First News - Trí Việt
                              </p>
                              <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                              <p className={styles["pro-price"]}>
                                <span className={styles["price"]}>58,000₫</span>
                                <span className={styles["price-del"]}>
                                  76,000₫
                                </span>
                              </p>
                            </div>
                            <div
                              className={styles["proloop-actions"]}
                              data-vrid={1079696682}
                            >
                              <div className={styles["proloop-actions__inner"]}>
                                <div className={styles["actions-primary"]}>
                                  <button
                                    type="submit"
                                    className={
                                      styles["btn-proloop-cart add-to-cart"]
                                    }
                                  >
                                    <span className={styles["btnadd"]}>
                                      Thêm vào giỏ
                                    </span>
                                    <span className={styles["btnico"]}>
                                      <svg
                                        id="svg"
                                        xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 -13 456.75885 456"
                                      >
                                        <path d="m150.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                        <path d="m446.855469 94.035156h-353.101563l-7.199218-40.300781c-4.4375-24.808594-23.882813-44.214844-48.699219-48.601563l-26.101563-4.597656c-5.441406-.96875-10.632812 2.660156-11.601562 8.097656-.964844 5.441407 2.660156 10.632813 8.101562 11.601563l26.199219 4.597656c16.53125 2.929688 29.472656 15.871094 32.402344 32.402344l35.398437 199.699219c4.179688 23.894531 24.941406 41.324218 49.199219 41.300781h210c22.0625.066406 41.546875-14.375 47.902344-35.5l47-155.800781c.871093-3.039063.320312-6.3125-1.5-8.898438-1.902344-2.503906-4.859375-3.980468-8-4zm-56.601563 162.796875c-3.773437 12.6875-15.464844 21.367188-28.699218 21.300781h-210c-14.566407.039063-27.035157-10.441406-29.5-24.800781l-24.699219-139.398437h336.097656zm0 0" />
                                        <path d="m360.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                      </svg>
                                    </span>
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className={styles["owl-item"]}
                        style={{
                          width: 220,
                          padding: 0,
                          border: "1px solid #eae4e8",
                        }}
                      >
                        <div className={styles["product-inner"]}>
                          <div
                            className={styles["product-books-1"]}
                            style={{ border: "none" }}
                          >
                            <div className={styles["proloop-img"]}>
                              <div className={styles["pro-soldout"]}>
                                <span style={{ width: 180 }}>Hết hàng</span>
                              </div>
                              <div
                                className={styles["img-product"]}
                                style={{ height: 215 }}
                              >
                                <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg" />
                              </div>
                              <div className={styles["img-sale"]}>
                                <img src=" https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                              </div>
                              .
                            </div>
                            <div className={styles["proloop-detail"]}>
                              <p className={styles["pro-vendor"]}>
                                First News - Trí Việt
                              </p>
                              <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                              <p className={styles["pro-price"]}>
                                <span className={styles["price"]}>58,000₫</span>
                                <span className={styles["price-del"]}>
                                  76,000₫
                                </span>
                              </p>
                            </div>
                            <div
                              className={styles["proloop-actions"]}
                              data-vrid={1079696682}
                            >
                              <div className={styles["proloop-actions__inner"]}>
                                <div className={styles["actions-primary"]}>
                                  <button
                                    type="submit"
                                    className={
                                      styles["btn-proloop-cart add-to-cart"]
                                    }
                                    style={{ width: 180 }}
                                    disabled
                                  >
                                    <span className={styles["btnsold"]}>
                                      Hết hàng
                                    </span>
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className={styles["owl-item"]}
                        style={{
                          width: 220,
                          padding: 0,
                          border: "1px solid #eae4e8",
                        }}
                      >
                        <div className={styles["product-inner"]}>
                          <div
                            className={styles["product-books-1"]}
                            style={{ border: "none" }}
                          >
                            <div className={styles["proloop-img"]}>
                              <div className={styles["pro-sale"]}>
                                <span>-24%</span>
                              </div>
                              <div
                                className={styles["img-product"]}
                                style={{ height: 215 }}
                              >
                                <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg" />
                              </div>
                              <div className={styles["img-sale"]}>
                                <img src=" https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                              </div>
                              .
                            </div>
                            <div className={styles["proloop-detail"]}>
                              <p className={styles["pro-vendor"]}>
                                First News - Trí Việt
                              </p>
                              <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                              <p className={styles["pro-price"]}>
                                <span className={styles["price"]}>58,000₫</span>
                                <span className={styles["price-del"]}>
                                  76,000₫
                                </span>
                              </p>
                            </div>
                            <div
                              className={styles["proloop-actions"]}
                              data-vrid={1079696682}
                            >
                              <div className={styles["proloop-actions__inner"]}>
                                <div className={styles["actions-primary"]}>
                                  <button
                                    type="submit"
                                    className={
                                      styles["btn-proloop-cart add-to-cart"]
                                    }
                                  >
                                    <span className={styles["btnadd"]}>
                                      Thêm vào giỏ
                                    </span>
                                    <span className={styles["btnico"]}>
                                      <svg
                                        id="svg"
                                        xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 -13 456.75885 456"
                                      >
                                        <path d="m150.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                        <path d="m446.855469 94.035156h-353.101563l-7.199218-40.300781c-4.4375-24.808594-23.882813-44.214844-48.699219-48.601563l-26.101563-4.597656c-5.441406-.96875-10.632812 2.660156-11.601562 8.097656-.964844 5.441407 2.660156 10.632813 8.101562 11.601563l26.199219 4.597656c16.53125 2.929688 29.472656 15.871094 32.402344 32.402344l35.398437 199.699219c4.179688 23.894531 24.941406 41.324218 49.199219 41.300781h210c22.0625.066406 41.546875-14.375 47.902344-35.5l47-155.800781c.871093-3.039063.320312-6.3125-1.5-8.898438-1.902344-2.503906-4.859375-3.980468-8-4zm-56.601563 162.796875c-3.773437 12.6875-15.464844 21.367188-28.699218 21.300781h-210c-14.566407.039063-27.035157-10.441406-29.5-24.800781l-24.699219-139.398437h336.097656zm0 0" />
                                        <path d="m360.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                      </svg>
                                    </span>
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className={styles["owl-item"]}
                        style={{
                          width: 220,
                          padding: 0,
                          border: "1px solid #eae4e8",
                        }}
                      >
                        <div className={styles["product-inner"]}>
                          <div
                            className={styles["product-books-1"]}
                            style={{ border: "none" }}
                          >
                            <div className={styles["proloop-img"]}>
                              <div className={styles["pro-sale"]}>
                                <span>-24%</span>
                              </div>
                              <div
                                className={styles["img-product"]}
                                style={{ height: 215 }}
                              >
                                <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg" />
                              </div>
                              <div className={styles["img-sale"]}>
                                <img src=" https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                              </div>
                              .
                            </div>
                            <div className={styles["proloop-detail"]}>
                              <p className={styles["pro-vendor"]}>
                                First News - Trí Việt
                              </p>
                              <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                              <p className={styles["pro-price"]}>
                                <span className={styles["price"]}>58,000₫</span>
                                <span className={styles["price-del"]}>
                                  76,000₫
                                </span>
                              </p>
                            </div>
                            <div
                              className={styles["proloop-actions"]}
                              data-vrid={1079696682}
                            >
                              <div className={styles["proloop-actions__inner"]}>
                                <div className={styles["actions-primary"]}>
                                  <button
                                    type="submit"
                                    className={
                                      styles["btn-proloop-cart add-to-cart"]
                                    }
                                  >
                                    <span className={styles["btnadd"]}>
                                      Thêm vào giỏ
                                    </span>
                                    <span className={styles["btnico"]}>
                                      <svg
                                        id="svg"
                                        xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 -13 456.75885 456"
                                      >
                                        <path d="m150.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                        <path d="m446.855469 94.035156h-353.101563l-7.199218-40.300781c-4.4375-24.808594-23.882813-44.214844-48.699219-48.601563l-26.101563-4.597656c-5.441406-.96875-10.632812 2.660156-11.601562 8.097656-.964844 5.441407 2.660156 10.632813 8.101562 11.601563l26.199219 4.597656c16.53125 2.929688 29.472656 15.871094 32.402344 32.402344l35.398437 199.699219c4.179688 23.894531 24.941406 41.324218 49.199219 41.300781h210c22.0625.066406 41.546875-14.375 47.902344-35.5l47-155.800781c.871093-3.039063.320312-6.3125-1.5-8.898438-1.902344-2.503906-4.859375-3.980468-8-4zm-56.601563 162.796875c-3.773437 12.6875-15.464844 21.367188-28.699218 21.300781h-210c-14.566407.039063-27.035157-10.441406-29.5-24.800781l-24.699219-139.398437h336.097656zm0 0" />
                                        <path d="m360.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                      </svg>
                                    </span>
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className={styles["owl-item"]}
                        style={{
                          width: 220,
                          padding: 0,
                          border: "1px solid #eae4e8",
                        }}
                      >
                        <div className={styles["product-inner"]}>
                          <div
                            className={styles["product-books-1"]}
                            style={{ border: "none" }}
                          >
                            <div className={styles["proloop-img"]}>
                              <div className={styles["pro-sale"]}>
                                <span>-24%</span>
                              </div>
                              <div
                                className={styles["img-product"]}
                                style={{ height: 215 }}
                              >
                                <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg" />
                              </div>
                              <div className={styles["img-sale"]}>
                                <img src=" https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                              </div>
                              .
                            </div>
                            <div className={styles["proloop-detail"]}>
                              <p className={styles["pro-vendor"]}>
                                First News - Trí Việt
                              </p>
                              <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                              <p className={styles["pro-price"]}>
                                <span className={styles["price"]}>58,000₫</span>
                                <span className={styles["price-del"]}>
                                  76,000₫
                                </span>
                              </p>
                            </div>
                            <div
                              className={styles["proloop-actions"]}
                              data-vrid={1079696682}
                            >
                              <div className={styles["proloop-actions__inner"]}>
                                <div className={styles["actions-primary"]}>
                                  <button
                                    type="submit"
                                    className={
                                      styles["btn-proloop-cart add-to-cart"]
                                    }
                                  >
                                    <span className={styles["btnadd"]}>
                                      Thêm vào giỏ
                                    </span>
                                    <span className={styles["btnico"]}>
                                      <svg
                                        id="svg"
                                        xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 -13 456.75885 456"
                                      >
                                        <path d="m150.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                        <path d="m446.855469 94.035156h-353.101563l-7.199218-40.300781c-4.4375-24.808594-23.882813-44.214844-48.699219-48.601563l-26.101563-4.597656c-5.441406-.96875-10.632812 2.660156-11.601562 8.097656-.964844 5.441407 2.660156 10.632813 8.101562 11.601563l26.199219 4.597656c16.53125 2.929688 29.472656 15.871094 32.402344 32.402344l35.398437 199.699219c4.179688 23.894531 24.941406 41.324218 49.199219 41.300781h210c22.0625.066406 41.546875-14.375 47.902344-35.5l47-155.800781c.871093-3.039063.320312-6.3125-1.5-8.898438-1.902344-2.503906-4.859375-3.980468-8-4zm-56.601563 162.796875c-3.773437 12.6875-15.464844 21.367188-28.699218 21.300781h-210c-14.566407.039063-27.035157-10.441406-29.5-24.800781l-24.699219-139.398437h336.097656zm0 0" />
                                        <path d="m360.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                      </svg>
                                    </span>
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className={styles["owl-item"]}
                        style={{
                          width: 220,
                          padding: 0,
                          border: "1px solid #eae4e8",
                        }}
                      >
                        <div className={styles["product-inner"]}>
                          <div
                            className={styles["product-books-1"]}
                            style={{ border: "none" }}
                          >
                            <div className={styles["proloop-img"]}>
                              <div className={styles["pro-sale"]}>
                                <span>-24%</span>
                              </div>
                              <div
                                className={styles["img-product"]}
                                style={{ height: 215 }}
                              >
                                <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg" />
                              </div>
                              <div className={styles["img-sale"]}>
                                <img src=" https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                              </div>
                              .
                            </div>
                            <div className={styles["proloop-detail"]}>
                              <p className={styles["pro-vendor"]}>
                                First News - Trí Việt
                              </p>
                              <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                              <p className={styles["pro-price"]}>
                                <span className={styles["price"]}>58,000₫</span>
                                <span className={styles["price-del"]}>
                                  76,000₫
                                </span>
                              </p>
                            </div>
                            <div
                              className={styles["proloop-actions"]}
                              data-vrid={1079696682}
                            >
                              <div className={styles["proloop-actions__inner"]}>
                                <div className={styles["actions-primary"]}>
                                  <button
                                    type="submit"
                                    className={
                                      styles["btn-proloop-cart add-to-cart"]
                                    }
                                  >
                                    <span className={styles["btnadd"]}>
                                      Thêm vào giỏ
                                    </span>
                                    <span className={styles["btnico"]}>
                                      <svg
                                        id="svg"
                                        xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 -13 456.75885 456"
                                      >
                                        <path d="m150.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                        <path d="m446.855469 94.035156h-353.101563l-7.199218-40.300781c-4.4375-24.808594-23.882813-44.214844-48.699219-48.601563l-26.101563-4.597656c-5.441406-.96875-10.632812 2.660156-11.601562 8.097656-.964844 5.441407 2.660156 10.632813 8.101562 11.601563l26.199219 4.597656c16.53125 2.929688 29.472656 15.871094 32.402344 32.402344l35.398437 199.699219c4.179688 23.894531 24.941406 41.324218 49.199219 41.300781h210c22.0625.066406 41.546875-14.375 47.902344-35.5l47-155.800781c.871093-3.039063.320312-6.3125-1.5-8.898438-1.902344-2.503906-4.859375-3.980468-8-4zm-56.601563 162.796875c-3.773437 12.6875-15.464844 21.367188-28.699218 21.300781h-210c-14.566407.039063-27.035157-10.441406-29.5-24.800781l-24.699219-139.398437h336.097656zm0 0" />
                                        <path d="m360.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                      </svg>
                                    </span>
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className={styles["owl-item"]}
                        style={{
                          width: 220,
                          padding: 0,
                          border: "1px solid #eae4e8",
                        }}
                      >
                        <div className={styles["product-inner"]}>
                          <div
                            className={styles["product-books-1"]}
                            style={{ border: "none" }}
                          >
                            <div className={styles["proloop-img"]}>
                              <div className={styles["pro-sale"]}>
                                <span>-24%</span>
                              </div>
                              <div
                                className={styles["img-product"]}
                                style={{ height: 215 }}
                              >
                                <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg" />
                              </div>
                              <div className={styles["img-sale"]}>
                                <img src=" https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                              </div>
                              .
                            </div>
                            <div className={styles["proloop-detail"]}>
                              <p className={styles["pro-vendor"]}>
                                First News - Trí Việt
                              </p>
                              <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                              <p className={styles["pro-price"]}>
                                <span className={styles["price"]}>58,000₫</span>
                                <span className={styles["price-del"]}>
                                  76,000₫
                                </span>
                              </p>
                            </div>
                            <div
                              className={styles["proloop-actions"]}
                              data-vrid={1079696682}
                            >
                              <div className={styles["proloop-actions__inner"]}>
                                <div className={styles["actions-primary"]}>
                                  <button
                                    type="submit"
                                    className={
                                      styles["btn-proloop-cart add-to-cart"]
                                    }
                                  >
                                    <span className={styles["btnadd"]}>
                                      Thêm vào giỏ
                                    </span>
                                    <span className={styles["btnico"]}>
                                      <svg
                                        id="svg"
                                        xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 -13 456.75885 456"
                                      >
                                        <path d="m150.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                        <path d="m446.855469 94.035156h-353.101563l-7.199218-40.300781c-4.4375-24.808594-23.882813-44.214844-48.699219-48.601563l-26.101563-4.597656c-5.441406-.96875-10.632812 2.660156-11.601562 8.097656-.964844 5.441407 2.660156 10.632813 8.101562 11.601563l26.199219 4.597656c16.53125 2.929688 29.472656 15.871094 32.402344 32.402344l35.398437 199.699219c4.179688 23.894531 24.941406 41.324218 49.199219 41.300781h210c22.0625.066406 41.546875-14.375 47.902344-35.5l47-155.800781c.871093-3.039063.320312-6.3125-1.5-8.898438-1.902344-2.503906-4.859375-3.980468-8-4zm-56.601563 162.796875c-3.773437 12.6875-15.464844 21.367188-28.699218 21.300781h-210c-14.566407.039063-27.035157-10.441406-29.5-24.800781l-24.699219-139.398437h336.097656zm0 0" />
                                        <path d="m360.355469 322.332031c-30.046875 0-54.402344 24.355469-54.402344 54.402344 0 30.042969 24.355469 54.398437 54.402344 54.398437 30.042969 0 54.398437-24.355468 54.398437-54.398437-.03125-30.03125-24.367187-54.371094-54.398437-54.402344zm0 88.800781c-19 0-34.402344-15.402343-34.402344-34.398437 0-19 15.402344-34.402344 34.402344-34.402344 18.996093 0 34.398437 15.402344 34.398437 34.402344 0 18.996094-15.402344 34.398437-34.398437 34.398437zm0 0" />
                                      </svg>
                                    </span>
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className={styles["owl-item"]}
                        style={{
                          width: 220,
                          padding: 0,
                          border: "1px solid #eae4e8",
                        }}
                      >
                        <div className={styles["product-inner"]}>
                          <div
                            className={styles["product-books-1"]}
                            style={{ border: "none" }}
                          >
                            <div className={styles["proloop-img"]}>
                              <div className={styles["pro-soldout"]}>
                                <span style={{ width: 180 }}>Hết hàng</span>
                              </div>
                              <div
                                className={styles["img-product"]}
                                style={{ height: 215 }}
                              >
                                <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/product-1_au7vwi.jpg" />
                              </div>
                              <div className={styles["img-sale"]}>
                                <img src=" https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/fashion02_frame_image_6842efd7e9b4493ea6dc78607f800ab9_ie3y5d.jpg" />
                              </div>
                              .
                            </div>
                            <div className={styles["proloop-detail"]}>
                              <p className={styles["pro-vendor"]}>
                                First News - Trí Việt
                              </p>
                              <h3>Hạnh Phúc Đến Từ Sự Biến Mất</h3>
                              <p className={styles["pro-price"]}>
                                <span className={styles["price"]}>58,000₫</span>
                                <span className={styles["price-del"]}>
                                  76,000₫
                                </span>
                              </p>
                            </div>
                            <div
                              className={styles["proloop-actions"]}
                              data-vrid={1079696682}
                            >
                              <div className={styles["proloop-actions__inner"]}>
                                <div className={styles["actions-primary"]}>
                                  <button
                                    type="submit"
                                    className={
                                      styles["btn-proloop-cart add-to-cart"]
                                    }
                                    style={{ width: 180 }}
                                  >
                                    <span className={styles["btnsold"]}>
                                      Hết hàng
                                    </span>
                                  </button>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
            <section className={styles["home-banner"]}>
              <div className={styles["container"]}>
                <div className={styles["banner-book"]}>
                  <div className={styles["img-book"]}>
                    <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/homebanner_1_img_lgn4bp.jpg" />
                  </div>
                  <div className={styles["img-book"]}>
                    <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484276/assignment-nextjs/homebanner_2_img_vf1s5n.jpg" />
                  </div>
                  <div className={styles["img-book"]}>
                    <img src="https://res.cloudinary.com/assjavascript/image/upload/v1658484277/assignment-nextjs/homebanner_3_img_j3u3jt.jpg" />
                  </div>
                </div>
              </div>
            </section>
            <section className={styles["home-blogs"]}>
              <div className={styles["container"]}>
                <div className={styles["section-heading"]}>
                  <div className={styles["box-header"]}>
                    <h2 className={styles["hTitle"]}>Bài Viết Mới Nhất</h2>
                  </div>
                </div>
                <div
                  className={styles["wrapper-content-1 row"]}
                  style={{ display: "flex" }}
                >
                  <div className={styles["wrap-left col-lg-6"]}>
                    <div className={styles["article-item"]}>
                      <div
                        className={styles["article-item__block"]}
                        style={{ width: 750 }}
                      >
                        <div className={styles["article-item__image"]}>
                          <div className={styles["art-image"]}>
                            <a
                              href="/blogs/news/24-tac-pham-xuat-sac-duoc-ton-vinh-tai-giai-sach-quoc-gia-lan-thu-tu"
                              title="24 tác phẩm xuất sắc được tôn vinh tại giải Sách Quốc gia lần thứ tư. Trong đó, nổi bật lên là chủ đề dành cho thiếu nhi với một giải A, 4 giải B, 2 giải C."
                              aria-label="24 tác phẩm xuất sắc được tôn vinh tại giải Sách Quốc gia lần thứ tư. Trong đó, nổi bật lên là chủ đề dành cho thiếu nhi với một giải A, 4 giải B, 2 giải C."
                            >
                              <picture>
                                <img
                                  style={{ width: 720 }}
                                  className={styles[" ls-is-cached lazyloaded"]}
                                  src="https://res.cloudinary.com/assjavascript/image/upload/v1658484274/assignment-nextjs/blog1_mwfenl.webp"
                                  title="24 tác phẩm xuất sắc được tôn vinh tại giải Sách Quốc gia lần thứ tư. Trong đó, nổi bật lên là chủ đề dành cho thiếu nhi với một giải A, 4 giải B, 2 giải C."
                                />
                              </picture>
                            </a>
                          </div>
                        </div>
                        <div
                          className={styles["article-item__detail"]}
                          style={{ padding: "0 15px 0 15px" }}
                        >
                          <h3 className={styles["art-title"]}>
                            <a href="/blogs/news/24-tac-pham-xuat-sac-duoc-ton-vinh-tai-giai-sach-quoc-gia-lan-thu-tu">
                              24 tác phẩm xuất sắc được tôn vinh tại giải Sách
                              Quốc gia lần thứ tư. Trong đó, nổi bật lên là chủ
                              đề dành cho thiếu nhi với một giải A, 4 giải B, 2
                              giải C.
                            </a>
                          </h3>
                          <div className={styles["art-meta"]}>
                            <span className={styles["art-date"]}>
                              <time dateTime="2021-11-26">
                                26 Tháng 11, 2021
                              </time>
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className={styles["wrap-right col-lg-6"]}>
                    <article className={styles["article-item"]}>
                      <div
                        className={styles["article-item__block"]}
                        style={{
                          display: "flex",
                        }}
                      >
                        <div className={styles["article-item__image"]}>
                          <div className={styles["art-image"]}>
                            <a
                              href="/blogs/news/bai-viet-mau-3"
                              title="Khuyến khích doanh nhân viết sách để lan tỏa kinh nghiệm, kiến thức"
                              aria-label="Khuyến khích doanh nhân viết sách để lan tỏa kinh nghiệm, kiến thức"
                            >
                              <img
                                style={{ width: 140 }}
                                className={styles[" ls-is-cached lazyloaded"]}
                                src="https://res.cloudinary.com/assjavascript/image/upload/v1658484275/assignment-nextjs/blog5_nkurbl.jpg"
                              />
                            </a>
                          </div>
                        </div>
                        <div
                          className={styles["article-item__detail"]}
                          style={{ marginTop: 19, marginLeft: 30 }}
                        >
                          <h3 className={styles["art-title"]}>
                            <a href="/blogs/news/bai-viet-mau-3">
                              Khuyến khích doanh nhân viết sách để lan tỏa kinh
                              nghiệm, kiến thức
                            </a>
                          </h3>
                          <div className={styles["art-meta"]}>
                            <span className={styles["art-date"]}>
                              <time dateTime="2021-11-25">
                                25 Tháng 11, 2021
                              </time>
                            </span>
                          </div>
                        </div>
                      </div>
                    </article>
                    <article className={styles["article-item"]}>
                      <div
                        className={styles["article-item__block"]}
                        style={{
                          display: "flex",
                        }}
                      >
                        <div className={styles["article-item__image"]}>
                          <div className={styles["art-image"]}>
                            <a
                              href="/blogs/news/bai-viet-mau-2"
                              title="Nhận thức mới về bảo đảm chủ quyền quốc gia trên không gian mạng"
                              aria-label="Nhận thức mới về bảo đảm chủ quyền quốc gia trên không gian mạng"
                            >
                              <img
                                style={{ width: 140 }}
                                className={styles[" lazyloaded"]}
                                src="https://res.cloudinary.com/assjavascript/image/upload/v1658484274/assignment-nextjs/blog4_j7mmbp.jpg"
                                title="Nhận thức mới về bảo đảm chủ quyền quốc gia trên không gian mạng"
                              />
                            </a>
                          </div>
                        </div>
                        <div
                          className={styles["article-item__detail"]}
                          style={{ marginTop: 19, marginLeft: 30 }}
                        >
                          <h3 className={styles["art-title"]}>
                            <a href="/blogs/news/bai-viet-mau-2">
                              Nhận thức mới về bảo đảm chủ quyền quốc gia trên
                              không gian mạng
                            </a>
                          </h3>
                          <div className={styles["art-meta"]}>
                            <span className={styles["art-date"]}>
                              <time dateTime="2021-11-25">
                                25 Tháng 11, 2021
                              </time>
                            </span>
                          </div>
                        </div>
                      </div>
                    </article>
                    <article className={styles["article-item"]}>
                      <div
                        className={styles["article-item__block"]}
                        style={{
                          display: "flex",
                        }}
                      >
                        <div className={styles["article-item__image"]}>
                          <div className={styles["art-image"]}>
                            <a
                              href="/blogs/news/nhung-cuon-sach-gianh-giai-thuong-sach-quoc-gia-lan-thu-tu"
                              title="Những cuốn sách giành Giải thưởng Sách quốc gia lần thứ tư"
                              aria-label="Những cuốn sách giành Giải thưởng Sách quốc gia lần thứ tư"
                            >
                              <img
                                style={{ width: 140 }}
                                className={styles[" lazyloaded"]}
                                src="https://res.cloudinary.com/assjavascript/image/upload/v1658484274/assignment-nextjs/blog3_xjny7f.jpg"
                                title="Những cuốn sách giành Giải thưởng Sách quốc gia lần thứ tư"
                              />
                            </a>
                          </div>
                        </div>
                        <div
                          className={styles["article-item__detail"]}
                          style={{ marginTop: 19, marginLeft: 30 }}
                        >
                          <h3 className={styles["art-title"]}>
                            <a href="/blogs/news/nhung-cuon-sach-gianh-giai-thuong-sach-quoc-gia-lan-thu-tu">
                              Những cuốn sách giành Giải thưởng Sách quốc gia
                              lần thứ tư
                            </a>
                          </h3>
                          <div className={styles["art-meta"]}>
                            <span className={styles["art-date"]}>
                              <time dateTime="2021-11-16">
                                16 Tháng 11, 2021
                              </time>
                            </span>
                          </div>
                        </div>
                      </div>
                    </article>
                    <article className={styles["article-item"]}>
                      <div
                        className={styles["article-item__block"]}
                        style={{
                          display: "flex"
                        }}
                      >
                        <div className={styles["article-item__image"]}>
                          <div className={styles["art-image"]}>
                            <a
                              href="/blogs/news/bo-viet-nam-danh-tac-them-bon-tac-pham"
                              title="Bộ 'Việt Nam danh tác' thêm bốn tác phẩm"
                              aria-label="Bộ 'Việt Nam danh tác' thêm bốn tác phẩm"
                            >
                              <img
                                style={{ width: 140 }}
                                className={styles[" ls-is-cached lazyloaded"]}
                                src="https://res.cloudinary.com/assjavascript/image/upload/v1658484274/assignment-nextjs/blo2_baqskl.jpg"
                              />
                            </a>
                          </div>
                        </div>
                        <div
                          className={styles["article-item__detail"]}
                          style={{ marginTop: 19, marginLeft: 30 }}
                        >
                          <h3 className={styles["art-title"]}>
                            <a href="/blogs/news/bo-viet-nam-danh-tac-them-bon-tac-pham">
                              Bộ 'Việt Nam danh tác' thêm bốn tác phẩm
                            </a>
                          </h3>
                          <div className={styles["art-meta"]}>
                            <span className={styles["art-date"]}>
                              <time dateTime="2021-11-16">
                                16 Tháng 11, 2021
                              </time>
                            </span>
                          </div>
                        </div>
                      </div>
                    </article>
                    <article className={styles["article-item"]}>
                      <div
                        className={styles["article-item__block"]}
                        style={{
                          display: "flex",
                        }}
                      >
                        <div className={styles["article-item__image"]}>
                          <div className={styles["art-image"]}>
                            <a
                              href="/blogs/news/lan-toa-nhung-cuon-sach-co-gia-tri"
                              title="Lan tỏa những cuốn sách có giá trị"
                              aria-label="Lan tỏa những cuốn sách có giá trị"
                            >
                              <img
                                style={{ width: 140 }}
                                className={styles[" lazyloaded"]}
                                src="https://res.cloudinary.com/assjavascript/image/upload/v1658484274/assignment-nextjs/blog1_mwfenl.webp"
                              />
                            </a>
                          </div>
                        </div>
                        <div
                          className={styles["article-item__detail"]}
                          style={{ marginTop: 19, marginLeft: 30 }}
                        >
                          <h3 className={styles["art-title"]}>
                            <a href="/blogs/news/lan-toa-nhung-cuon-sach-co-gia-tri">
                              Lan tỏa những cuốn sách có giá trị
                            </a>
                          </h3>
                          <div className={styles["art-meta"]}>
                            <span className={styles["art-date"]}>
                              <time dateTime="2021-11-16">
                                16 Tháng 11, 2021
                              </time>
                            </span>
                          </div>
                        </div>
                      </div>
                    </article>
                  </div>
                </div>
              </div>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
